name: deploy

on:
  push:
    branches-ignore:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Prepare git log message to avoid extra blank lines
      - name: Set env message
        run: |
          GITREPO=`git remote show origin -n | grep h.URL | sed 's/Fetch URL: https:\/\/github.com\/crux-arm\/crux-ports-//g'`
          GITMSG=`git log -1 --pretty=format:"%s"`
          GITBRANCH=`git branch | grep '*' | sed 's/* //'`
          echo "MESSAGE=$(echo "[$GITREPO/$GITBRANCH  ]: $GITMSG")" >> $GITHUB_ENV

      # Send IRC message by bot
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: ${{ github.event_name == 'push' }}
        with:
          channel: "#crux-riscv"
          server: "irc.libera.chat"
          nickname: crux-riscv-bot
          message: ${{ env.MESSAGE }}
